#ifndef MVH_UTIL_H
#define MVH_UTIL_H

#include <stdint.h>

void *mvh_mem_zero(void *destination, uint64_t size);
void *mvh_mem_set(void *destination, uint8_t value, uint64_t size);
void *mvh_mem_copy(void *destination, const void *source, uint64_t size);
void *mvh_mem_move(void *destination, const void *source, uint64_t size);
int mvh_mem_compare(const void *left, const void *right, uint64_t size);
void mvh_mem_swap(void *left, void *right, uint64_t size);
const void *mvh_mem_find(const void *memory, uint8_t value, uint64_t size);
void *mvh_mem_reverse(void *memory, uint64_t size);
int mvh_mem_is_zero(const void *memory, uint64_t size);
void *mvh_mem_xor(void *destination, const void *source, uint64_t size);
int mvh_mem_copy_checked(void *destination, uint64_t destination_size, const void *source,
                         uint64_t size);
int mvh_mem_equal(const void *left, const void *right, uint64_t size);
void mvh_mem_fill16(uint16_t *destination, uint16_t value, uint64_t count);
void mvh_mem_fill32(uint32_t *destination, uint32_t value, uint64_t count);
uint64_t mvh_mem_count_byte(const void *memory, uint8_t value, uint64_t size);
uint64_t mvh_mem_hash_fnv1a64(const void *memory, uint64_t size);

uint64_t mvh_str_length(const char *text);
uint64_t mvh_str_nlength(const char *text, uint64_t limit);
int mvh_str_equal(const char *left, const char *right);
int mvh_str_nequal(const char *left, const char *right, uint64_t limit);
int mvh_str_compare(const char *left, const char *right);
int mvh_str_ncompare(const char *left, const char *right, uint64_t limit);
uint64_t mvh_str_copy(char *destination, uint64_t capacity, const char *source);
uint64_t mvh_str_ncopy(char *destination, uint64_t capacity, const char *source,
                       uint64_t source_limit);
uint64_t mvh_str_concat(char *destination, uint64_t capacity, const char *source);
const char *mvh_str_find_char(const char *text, char character);
const char *mvh_str_rfind_char(const char *text, char character);
int mvh_str_starts_with(const char *text, const char *prefix);
int mvh_str_ends_with(const char *text, const char *suffix);
int mvh_str_contains(const char *text, const char *needle);
uint64_t mvh_str_count_char(const char *text, char character);
const char *mvh_str_trim_left(const char *text);
uint64_t mvh_str_trim_right(char *text);
void mvh_str_to_upper(char *text);
void mvh_str_to_lower(char *text);
uint64_t mvh_str_replace_char(char *text, char old_character, char new_character);
int mvh_str_split_once(const char *text, char separator, char *left, uint64_t left_capacity,
                       char *right, uint64_t right_capacity);
uint64_t mvh_str_join(char *destination, uint64_t capacity, const char *left,
                      const char *separator, const char *right);
int mvh_str_is_empty(const char *text);
uint32_t mvh_str_hash_fnv1a32(const char *text);
uint64_t mvh_str_hash_fnv1a64(const char *text);
uint64_t mvh_str_common_prefix(const char *left, const char *right);
const char *mvh_str_find(const char *text, const char *needle);
void mvh_str_reverse(char *text);
int64_t mvh_str_index_char(const char *text, char character);
int64_t mvh_str_last_index_char(const char *text, char character);
int mvh_str_case_equal(const char *left, const char *right);
int mvh_str_ncase_equal(const char *left, const char *right, uint64_t limit);
const char *mvh_str_skip_space(const char *text);
int mvh_str_next_token(const char **cursor, char *token, uint64_t capacity);
int mvh_parse_i64(const char *text, int64_t *result);
uint64_t mvh_format_u64(char *destination, uint64_t capacity, uint64_t value);
uint64_t mvh_format_hex_u64(char *destination, uint64_t capacity, uint64_t value);
uint64_t mvh_str_normalize_slashes(char *text);

int mvh_ascii_is_upper(char character);
int mvh_ascii_is_lower(char character);
int mvh_ascii_is_alpha(char character);
int mvh_ascii_is_digit(char character);
int mvh_ascii_is_alnum(char character);
int mvh_ascii_is_space(char character);
int mvh_ascii_is_hex(char character);
int mvh_ascii_is_printable(char character);
int mvh_ascii_is_control(char character);
int mvh_ascii_is_punctuation(char character);
int mvh_ascii_is_graph(char character);
int mvh_ascii_is_binary(char character);
char mvh_ascii_to_upper(char character);
char mvh_ascii_to_lower(char character);
int mvh_ascii_digit_value(char character);
int mvh_ascii_hex_value(char character);

uint64_t mvh_min_u64(uint64_t left, uint64_t right);
uint64_t mvh_max_u64(uint64_t left, uint64_t right);
uint64_t mvh_clamp_u64(uint64_t value, uint64_t minimum, uint64_t maximum);
uint64_t mvh_align_up_u64(uint64_t value, uint64_t alignment);
uint64_t mvh_align_down_u64(uint64_t value, uint64_t alignment);
int mvh_is_power_of_two_u64(uint64_t value);
uint64_t mvh_next_power_of_two_u64(uint64_t value);
int mvh_checked_add_u64(uint64_t left, uint64_t right, uint64_t *result);
int mvh_checked_mul_u64(uint64_t left, uint64_t right, uint64_t *result);
uint32_t mvh_rotate_left32(uint32_t value, uint32_t shift);
uint32_t mvh_rotate_right32(uint32_t value, uint32_t shift);
uint64_t mvh_rotate_left64(uint64_t value, uint32_t shift);
uint64_t mvh_rotate_right64(uint64_t value, uint32_t shift);
uint32_t mvh_popcount32(uint32_t value);
uint32_t mvh_popcount64(uint64_t value);
uint16_t mvh_bswap16(uint16_t value);
uint32_t mvh_bswap32(uint32_t value);
uint64_t mvh_bswap64(uint64_t value);
int mvh_parse_u64(const char *text, uint64_t *result);
int mvh_parse_hex_u64(const char *text, uint64_t *result);
uint32_t mvh_min_u32(uint32_t left, uint32_t right);
uint32_t mvh_max_u32(uint32_t left, uint32_t right);
uint32_t mvh_clamp_u32(uint32_t value, uint32_t minimum, uint32_t maximum);
uint64_t mvh_abs_i64(int64_t value);
uint64_t mvh_gcd_u64(uint64_t left, uint64_t right);
int mvh_checked_lcm_u64(uint64_t left, uint64_t right, uint64_t *result);
uint64_t mvh_ceil_div_u64(uint64_t numerator, uint64_t denominator);
uint64_t mvh_round_up_multiple_u64(uint64_t value, uint64_t multiple);
uint64_t mvh_round_down_multiple_u64(uint64_t value, uint64_t multiple);
int mvh_checked_sub_u64(uint64_t left, uint64_t right, uint64_t *result);
int mvh_checked_add_i64(int64_t left, int64_t right, int64_t *result);
int mvh_checked_mul_i64(int64_t left, int64_t right, int64_t *result);
int mvh_log2_floor_u64(uint64_t value);
int mvh_log2_ceil_u64(uint64_t value);
uint32_t mvh_count_leading_zero32(uint32_t value);
uint32_t mvh_count_trailing_zero32(uint32_t value);
uint64_t mvh_bit_set64(uint64_t value, uint32_t bit);
uint64_t mvh_bit_clear64(uint64_t value, uint32_t bit);
int mvh_bit_test64(uint64_t value, uint32_t bit);
uint64_t mvh_bit_toggle64(uint64_t value, uint32_t bit);
uint64_t mvh_mask_range64(uint32_t offset, uint32_t width);
uint32_t mvh_parity32(uint32_t value);
uint32_t mvh_parity64(uint64_t value);
uint16_t mvh_load_le16(const void *memory);
uint32_t mvh_load_le32(const void *memory);
uint64_t mvh_load_le64(const void *memory);
void mvh_store_le16(void *memory, uint16_t value);
void mvh_store_le32(void *memory, uint32_t value);
void mvh_store_le64(void *memory, uint64_t value);
uint16_t mvh_load_be16(const void *memory);
uint32_t mvh_load_be32(const void *memory);
uint64_t mvh_load_be64(const void *memory);
void mvh_store_be16(void *memory, uint16_t value);
void mvh_store_be32(void *memory, uint32_t value);
void mvh_store_be64(void *memory, uint64_t value);
int64_t mvh_min_i64(int64_t left, int64_t right);
int64_t mvh_max_i64(int64_t left, int64_t right);
int64_t mvh_clamp_i64(int64_t value, int64_t minimum, int64_t maximum);
uint64_t mvh_saturating_add_u64(uint64_t left, uint64_t right);
uint64_t mvh_saturating_sub_u64(uint64_t left, uint64_t right);
uint64_t mvh_saturating_mul_u64(uint64_t left, uint64_t right);
uint64_t mvh_div_round_nearest_u64(uint64_t numerator, uint64_t denominator);
int mvh_is_even_u64(uint64_t value);
int mvh_is_odd_u64(uint64_t value);
int mvh_fibonacci_u64(uint32_t index, uint64_t *result);
int mvh_factorial_u64(uint32_t value, uint64_t *result);
int mvh_pow_u64(uint64_t base, uint32_t exponent, uint64_t *result);
uint64_t mvh_integer_sqrt_u64(uint64_t value);
uint64_t mvh_average_u64(uint64_t left, uint64_t right);
int mvh_sign_i64(int64_t value);
uint32_t mvh_count_leading_zero64(uint64_t value);
uint32_t mvh_count_trailing_zero64(uint64_t value);
uint32_t mvh_reverse_bits32(uint32_t value);
uint64_t mvh_reverse_bits64(uint64_t value);
uint64_t mvh_extract_bits64(uint64_t value, uint32_t offset, uint32_t width);
uint64_t mvh_insert_bits64(uint64_t original, uint64_t field, uint32_t offset,
                           uint32_t width);
int mvh_next_set_bit64(uint64_t value, uint32_t start);
int mvh_previous_set_bit64(uint64_t value, uint32_t start);
int64_t mvh_sign_extend64(uint64_t value, uint32_t width);
uint32_t mvh_count_byte64(uint64_t value, uint8_t byte);

#endif
