#ifndef MVH_VERSION_H
#define MVH_VERSION_H

#define MVH_KERNEL_NAME "MVH Kernel"
#define MVH_KERNEL_VERSION "1.1.5"
#define MVH_KERNEL_ARCH "x86_64"
#define MVH_KERNEL_FORMAT "ELF64"
#define MVH_KERNEL_ABI_VERSION 2u
#define MVH_KERNEL_ABI_STRING "2"
#define MVH_KERNEL_BUILD_ID "mvh-1.1.5"

#define MVH_KERNEL_VERSION_MAJOR 1u
#define MVH_KERNEL_VERSION_MINOR 1u
#define MVH_KERNEL_VERSION_PATCH 5u

#endif
