#ifndef MVH_VERSION_H
#define MVH_VERSION_H

#define MVH_KERNEL_NAME "MVH Kernel"
#define MVH_KERNEL_VERSION "1.1.4"
#define MVH_KERNEL_ARCH "x86_64"
#define MVH_KERNEL_FORMAT "ELF64"

#define MVH_KERNEL_VERSION_MAJOR 1u
#define MVH_KERNEL_VERSION_MINOR 1u
#define MVH_KERNEL_VERSION_PATCH 4u

#endif
